name: Deploy project
on: [push, workflow_dispatch]
jobs: # just use one job
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      # - name: install NodeJS  # not necessary the checkout@v3 includes the NodeJS
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run test
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ...."